trigger:
  branches:
    include:
      - development #only run on development branch

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.12"

  - script: | # install dependencies from requirements.txt file
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: | #run pylint on the app directory disabling specific warnings
      pylint app --disable=missing-module-docstring,missing-function-docstring
    displayName: "Run Pylint"

  - script: | # set PYTHONPATH to include source directory and run pytest
      export PYTHONPATH=$PYTHONPATH:$(Build.SourcesDirectory) 
      pytest
    displayName: "Run tests"
